msgid ""
msgstr ""
"Project-Id-Version: scikit-learn\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-03-31 11:24-0400\n"
"PO-Revision-Date: 2021-06-06 23:44\n"
"Last-Translator: \n"
"Language-Team: Spanish\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.9.0\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Crowdin-Project: scikit-learn\n"
"X-Crowdin-Project-ID: 450526\n"
"X-Crowdin-Language: es-ES\n"
"X-Crowdin-File: /main/doc/en/modules/generated/sklearn.exceptions.NotFittedError.po\n"
"X-Crowdin-File-ID: 5436\n"
"Language: es_ES\n"

#: ../modules/generated/sklearn.exceptions.NotFittedError.rst:2
msgid ":mod:`sklearn.exceptions`.NotFittedError"
msgstr ":mod:`sklearn.exceptions`.NotFittedError"

#: of sklearn.exceptions.NotFittedError:2
msgid "Exception class to raise if estimator is used before fitting."
msgstr "Clase de excepción que se lanza si se utiliza el estimador antes del ajuste."

#: of sklearn.exceptions.NotFittedError:4
msgid "This class inherits from both ValueError and AttributeError to help with exception handling and backward compatibility."
msgstr "Esta clase hereda tanto de ValueError como de AttributeError para ayudar con el manejo de excepciones y la compatibilidad con versiones anteriores."

#: of sklearn.exceptions.NotFittedError
msgid "Attributes"
msgstr "Atributos"

#: of sklearn.exceptions.NotFittedError:20
msgid "**args**"
msgstr "**args**"

#: of sklearn.exceptions.NotFittedError:23
msgid "Examples"
msgstr "Ejemplos"

#: of sklearn.exceptions.NotFittedError:33
msgid "Moved from sklearn.utils.validation."
msgstr "Se ha movido de sklearn.utils.validation."

#: of sklearn.exceptions.NotFittedError:37
msgid "Methods"
msgstr "Métodos"

#: of sklearn.exceptions.NotFittedError:41:<autosummary>:1
msgid ":obj:`with_traceback <sklearn.exceptions.NotFittedError.with_traceback>`\\"
msgstr ":obj:`with_traceback <sklearn.exceptions.NotFittedError.with_traceback>`\\"

#: of sklearn.exceptions.NotFittedError.with_traceback:2
#: sklearn.exceptions.NotFittedError:41:<autosummary>:1
msgid "Exception.with_traceback(tb) -- set self.__traceback__ to tb and return self."
msgstr "Exception.with_traceback(tb) -- se establece self.__traceback__ en tb y devuelve self."

